spring.application.name=produto-service

spring.cloud.config.uri=http://localhost:8888
spring.config.import=configserver:http://localhost:8888

spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/produto?authSource=admin

application-version=1.0.0
